
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.01
name: Task-Business-AU
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.42
  File::Spec: 0.80
requires: 
  Business::AU::ACN: 0.28
  SMS::Send::AU::MyVodafone: 0.02
  Business::AU::ABN: 1.05
  Date::Holidays::AU: 0.04
  Business::AU::TFN: 0.1
  SMS::Send: 0.03
abstract: A Task module for Australian Businesses
