--- 
abstract: A Task module for Australian Businesses
author: 
  - Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Business-AU
no_index: 
  directory: 
    - inc
    - t
requires: 
  Business::AU::ABN: 1.05
  Business::AU::ACN: 0.28
  Business::AU::TFN: 0.1
  Date::Holidays::AU: 0.04
  SMS::Send: 0.03
  SMS::Send::AU::MyVodafone: 0.02
version: 0.02
